VehicleCollision/Components/CrashSeverityViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VehicleCollision.Models;

namespace VehicleCollision.Components
{
	public class CrashSeverityViewComponent : ViewComponent
	{
		private ICollisionRepository _repo { get; set; }
		public CrashSeverityViewComponent(ICollisionRepository temp)
		{
			_repo = temp;
		}

		public IViewComponentResult Invoke()
		{
			ViewBag.SelectCrashSeverity = RouteData?.Values["severity"];

			var crashseverity = _repo.CrashSeverity
			.Select(x => x.Description)
			.Distinct()
			.OrderBy(x => x);
			return View(crashseverity);
		}
	}
}

VehicleCollision/Controllers/DataAnalyticsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.Tensors;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VehicleCollision.Models.DataAnalytics;

namespace VehicleCollision.Controllers
{
    public class DataAnalyticsController : Controller
    {
        private InferenceSession _session;

        public DataAnalyticsController(InferenceSession session)
        {
            _session = session;
        }
        public IActionResult Index()
        {
            return View("LandingPage");
        }
        
        [HttpGet]
        public IActionResult SeverityPredicter()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SeverityPredicter(SeverityPrediction data)
        {
            new InferenceSession("Models/DataAnalytics/XGBoostClassifierModel.onnx");

            var result = _session.Run(new List<NamedOnnxValue>
            {
                NamedOnnxValue.CreateFromTensor("float_input", data.AsTensor())
            });

            Tensor<long> score = result.First().AsTensor<long>();
            var prediction = new Prediction { PredictionValue = score.First() };
            result.Dispose();

            return View("Result", prediction);
        }

        public IActionResult Analytics()
        {
            return View("Visualizations");
        }

        public IActionResult Vehicles()
        {
            new InferenceSession("Models/DataAnalytics/HGBoostClassifierModel.onnx");

            return View();
        }
    }

}

VehicleCollision/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using VehicleCollision.Models;
using VehicleCollision.Models.ViewModels;

namespace VehicleCollision.Controllers
{
    public class HomeController : Controller
    {
        private ICollisionRepository _repo { get; set; }

        public HomeController(ICollisionRepository temp)
        {
            _repo = temp;
        }

        public IActionResult Index(string severity, int pageNum = 1)
        {
            //int pageSize = 25;
            //var crashes = new CrashesViewModel
            //{
            //    Crashes = _repo.Crashes
            //    //.Where(cs => cs.CrashSeverity == severity || severity == null)
            //    .OrderBy(c => c.CrashId)
            //    .Skip((pageNum - 1) * pageSize)
            //    .Take(10)
            //    , //pageSize

            //    PageInfo = new PageInfo
            //    {
            //        TotalNumCrashes = 100,
            //        CrashesPerPage = pageSize,
            //        CurrentPage = pageNum
            //    }
            //};

            return View();

        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult CollisionData(string severity, int pageNum = 1)
        {

            int pageSize = 25;
            var crashes = new CrashesViewModel
            {
                Crashes = _repo.Crashes
                .Include(x => x.CrashSeverity)
                .Where(x => x.CrashSeverity.Description == severity || severity == null)
                .OrderBy(c => c.CrashId)
                .Skip((pageNum - 1) * pageSize)
                .Take(pageSize)
                , //pageSize

                PageInfo = new PageInfo
                {

                    TotalNumCrashes = (severity == null ? _repo.Crashes.Count() / 10000 : _repo.Crashes.Where(x => x.CrashSeverity.Description == severity).Count() / 10000),
                    CrashesPerPage = pageSize,
                    CurrentPage = pageNum
                }
            };
            //ViewBag.CrashSeverity = _repo.CrashSeverities.ToList();

            return View(crashes);
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }
        [Authorize(Roles = "Community, Administrator")]
        public IActionResult Community()
        {
            return View();
        }
  
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

VehicleCollision/Pages/CollisionData.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace VehicleCollision.Pages
{
    public class CollisionDataModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

VehicleCollision/Views/Home/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "About Us";
}

<!--Team members section-->
<section class="py-5">
    <div class="container px-5 my-5">
        <div class="text-center">
            <h2 class="fw-bolder">Our Team</h2>
            <p class="lead fw-normal text-muted mb-5">Dedicated to building a better Utah</p>
        </div>
        <div class="row gx-5 row-cols-1 row-cols-sm-2 row-cols-xl-4 justify-content-center">
            <div class="col mb-5 mb-5 mb-xl-0">
                <div class="text-center">
                    <img class="img-fluid rounded-circle mb-4 px-4" src="~/img/lane-alicia.jpg" alt="Alicia Lane" />
                    <h5 class="fw-bolder">Alicia Lane</h5>
                    <div class="fst-italic text-muted"></div>
                </div>
            </div>
            <div class="col mb-5 mb-5 mb-xl-0">
                <div class="text-center">
                    <img class="img-fluid rounded-circle mb-4 px-4" src="~/img/donaldson-jacob.jpg" alt="Jacob Donaldson" />
                    <h5 class="fw-bolder">Jacob Donaldson</h5>
                    <div class="fst-italic text-muted"></div>
                </div>
            </div>
            <div class="col mb-5 mb-5 mb-sm-0">
                <div class="text-center">
                    <img class="img-fluid rounded-circle mb-4 px-4" src="~/img/kinghorn-jessica.jpg" alt="Jessica Kinghorn" />
                    <h5 class="fw-bolder">Jessica Kinghorn</h5>
                    <div class="fst-italic text-muted"></div>
                </div>
            </div>
            <div class="col mb-5">
                <div class="text-center">
                    <img class="img-fluid rounded-circle mb-4 px-4" src="~/img/perry-matthew.jpg" alt="Matt Perry" />
                    <h5 class="fw-bolder">Matt Perry</h5>
                    <div class="fst-italic text-muted"></div>
                </div>
            </div>
        </div>
    </div>
</section>

VehicleCollision/Views/Home/CollisionData.cshtml
@{
    ViewData["Title"] = "Collision Data";
}

@model CrashesViewModel

<div class="row m-1 p-1">
    <div id="crashseverity" class="col-2">
        <h5 class="text-center">Collision Severity</h5>
        <vc:crash-severity></vc:crash-severity>

    </div>

    <div class="col-10">
        <h1>Collisions</h1>
        <div page-number="@Model.PageInfo" page-action="CollisionData" page-class-enabled="true" page-class="btn"
             page-class-normal="btn-outline-dark" page-class-selected="btn-primary" class="btn-group pull-right m-1"></div>

        <div></div>

<table class="table table-responsive table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <td>Date/Time</td>
            <td>Route</td>
            <td>Milepoint</td>
            <td>Location (lat/long)</td>
            <td>Road Name</td>
            <td>City</td>
            <td>County</td>
            <td>Crash Severity</td>
            <td>Tags</td>
        </tr>
    </thead>
    <tbody>
       
        @foreach (var c in Model.Crashes)
        {
            <tr>
                <td>@c.CrashDatetime</td>
                <td>@c.Route</td>
                <td>@c.Milepoint</td>
                <td>@c.LatUtmY, @c.LongUtmX</td>
                <td>@c.MainRoadName</td>
                <td>@c.City</td>
                <td>@c.CountyName</td>
                <td>@c.CrashSeverity.Description</td>
                <td>
                    @if (c.WorkZoneRelated)
                    {<p>Work-Zone Related</p>}
                    @if (c.PedestrianInvolved)
                    {<p>Pedestrian Involved</p>}
                    @if (c.BicyclistInvolved)
                    {<p>Bicyclist Involved</p>}
                    @if (c.MotorcycleInvolved)
                    {<p>Motorcycle Involved</p>}
                    @if (c.ImproperRestraint)
                    {<p>Improper Restraint</p>}
                    @if (c.Unrestrained)
                    {<p>Unrestrained</p>}
                    @if (c.Dui)
                    {<p>DUI</p>}
                    @if (c.IntersectionRelated)
                    {<p>Intersection Related</p>}
                    @if (c.WildAnimalRelated)
                    {<p>Wild Animal Related</p>}
                    @if (c.DomesticAnimalRelated)
                    {<p>Domestic Animal Related</p>}
                    @if (c.OverturnRollover)
                    {<p>Overturn Rollover</p>}
                    @if (c.CommercialMotorVehInvolved)
                    {<p>Commercial Motor Vehicle Involved</p>}
                    @if (c.TeenageDriverInvolved)
                    {<p>TeenageDriverInvolved</p>}
                    @if (c.OlderDriverInvolved)
                    {<p>Older Driver Involving</p>}
                    @if (c.NightDarkCondition)
                    {<p>Night Dark Condition</p>}
                    @if (c.SingleVehicle)
                    {<p>Single Vehicle</p>}
                    @if (c.DistractedDriving)
                    {<p>Distracted Driving</p>}
                    @if (c.DrowsyDriving)
                    {<p>Drowsy Driving</p>}
                    @if (c.RoadwayDeparture)
                    {<p>Roadway Departure</p>}
                </td>
            </tr>
        }
    </tbody>
</table>

        <div page-number="@Model.PageInfo" page-action="CollisionData" page-class-enabled="true" page-class="btn"
             page-class-normal="btn-outline-dark" page-class-selected="btn-primary" class="btn-group pull-right m-1"></div>

    </div>
</div>

VehicleCollision/Views/Home/Community.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Welcome to the Community</h1>
<p>
    In the future this page will allow community members to share thoughts, stories, or events related to vehicle collisions in Utah. Sit down, chat, find solutions, and have a nice cold rootbeer.
</p>

VehicleCollision/Views/Home/Contact.cshtml
<!-- Start Banner Hero -->
    <section class="bg-light">
        <div class="container py-4">
            <div class="row align-items-center justify-content-between">
                <div class="contact-header col-lg-4">
                    <h1 class="h2 pb-3 text-primary">Contact</h1>
                    <h3 class="h4 regular-400">Need Help? Have A Question?</h3>
                    <p class="light-300">
                        Fill out the form below and we will get back to you within 1-2 business days.
                    </p>
                </div>
                <div class="contact-img col-lg-5 align-items-end col-md-4">

                    <img class="img-fluid" src="~/img/trafficcircle.jpg" />
                </div>
            </div>
        </div>
    </section>
    <!-- End Banner Hero -->

    <!-- Start Contact -->
    <section class="container py-5">

        @*<h1 class="col-12 col-xl-8 h2 text-left text-primary pt-3">Create success campaign with us!</h1>
        <h2 class="col-12 col-xl-8 h4 text-left regular-400">Elit, sed do eiusmod tempor </h2>
        <p class="col-12 col-xl-8 text-left text-muted pb-5 light-300">
            Incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices
            gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. Laboris
            nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit
            in voluptate.
        </p>*@

        <div class="row pb-4">
            @*<div class="col-lg-4">

                <div class="contact row mb-4">
                    <div class="contact-icon col-lg-3 col-3">
                        <div class="py-3 mb-2 text-center border rounded text-secondary">
                            <i class='display-6 bx bx-news'></i>
                        </div>
                    </div>
                    <ul class="contact-info list-unstyled col-lg-9 col-9  light-300">
                        <li class="h5 mb-0">Media Contact</li>
                        <li class="text-muted">Mr. John Doe</li>
                        <li class="text-muted">010-020-0340</li>
                    </ul>
                </div>

                <div class="contact row mb-4">
                    <div class="contact-icon col-lg-3 col-3">
                        <div class="border py-3 mb-2 text-center border rounded text-secondary">
                            <i class='bx bx-laptop display-6' ></i>
                        </div>
                    </div>
                    <ul class="contact-info list-unstyled col-lg-9 col-9 light-300">
                        <li class="h5 mb-0">Technical Contact</li>
                        <li class="text-muted">Mr. John Stiles</li>
                        <li class="text-muted">010-020-0340</li>
                    </ul>
                </div>

                <div class="contact row mb-4">
                    <div class="contact-icon col-lg-3 col-3">
                        <div class="border py-3 mb-2 text-center border rounded text-secondary">
                            <i class='bx bx-money display-6'></i>
                        </div>
                    </div>
                    <ul class="contact-info list-unstyled col-lg-9 col-9 light-300">
                        <li class="h5 mb-0">Billing Contact</li>
                        <li class="text-muted">Mr. Richard Miles</li>
                        <li class="text-muted">010-020-0340</li>
                    </ul>
                </div>

            </div>*@


            <!-- Start Contact Form -->
            <div class="col-lg-8 ">
                <iframe class="airtable-embed" src="https://airtable.com/embed/shrDWBWJASdb16p7z?backgroundColor=red" frameborder="0" onmousewheel="" width="100%" height="900" style="background: transparent; border: 1px solid #ccc;"></iframe>
            </div>
            <!-- End Contact Form -->


        </div>
    </section>
    <!-- End Contact -->

VehicleCollision/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}


 <!-- Start Banner Hero -->
    <div class="banner-wrapper bg-light">
        <div id="index_banner" class="banner-vertical-center-index container-fluid pt-5">

            <!-- Start slider -->
            <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"></li>
                    <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"></li>
                    <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">

                        <div class="py-5 row d-flex align-items-center">
                            <div class="banner-content col-lg-8 col-8 offset-2 m-lg-auto text-left py-5 pb-5 bg-light bg-gradient">
                                <h1 class="banner-heading h1 text-secondary display-3 mb-0 pb-5 mx-0 px-0 light-300 typo-space-line">
                                    Stop <strong>Crashes</strong> 
                              </h1>
                                <p class="banner-body text-muted py-3 mx-0 px-0">
                                    The Utah Motor Vehicle Collision site is dedicated to helping Utah drive safer.

                              </p>
                                <a class="banner-button btn rounded-pill btn-outline-primary btn-lg px-4" asp-area="" asp-controller="Home" asp-action="About" role="button">About Us</a>
                            </div>
                        </div>

                    </div>
                    <div class="carousel-item">

                        <div class="py-5 row d-flex align-items-center">

                            <div class="banner-content col-lg-8 col-8 offset-2 m-lg-auto text-left py-5 pb-5 bg-light bg-gradient">
                                <h1 class="banner-heading h1 text-secondary display-3 mb-0 pb-3 mx-0 px-0 light-300">
                                    View Utah Driver Collision Data
                                </h1>
                                <p class="banner-body text-muted py-3">
                                    We have the latest data available for vehicle collisions in Utah

                                </p>
                                <a class="banner-button btn rounded-pill btn-outline-primary btn-lg px-4" asp-controller="Home" asp-action="CollisionData" role="button">View Data</a>
                            </div>
                        </div>

                    </div>
                    <div class="carousel-item">

                        <div class="py-5 row d-flex align-items-center">
                            <div class="banner-content col-lg-8 col-8 offset-2 m-lg-auto text-left py-5 pb-5 bg-light bg-gradient">
                                <h1 class="banner-heading h1 text-secondary display-3 mb-0 pb-3 mx-0 px-0 light-300">
                                   Yeet On The Slopes NOT in the Car
                                </h1>
                                <p class="banner-body text-muted py-3">
                                    1,000s of people die each year by being ejected from the car. Wear a seat belt make others who ride with you do the same.
                                </p>
                                <a class="banner-button btn rounded-pill btn-outline-primary btn-lg px-4" asp-controller="DataAnalytics" asp-action="Index" role="button">Data Analytics</a>
                            </div>
                        </div>

                    </div>
                </div>
                <a class="carousel-control-prev text-decoration-none" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
                    <i class='bx bx-chevron-left'></i>
                    <span class="visually-hidden">Previous</span>
                </a>
                <a class="carousel-control-next text-decoration-none" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
                    <i class='bx bx-chevron-right'></i>
                    <span class="visually-hidden">Next</span>
                </a>
            </div>
            <!-- End slider -->

        </div>
    </div>
    <!-- End Banner Hero -->